# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main function
#'
#' @param Y, n-by-p count matrix
#' @param z, phonotype group vector
#' @param s, initial size factor vector
#' @param iter, number of MCMC iteration
#' @param DPP, if use DPP for normalization
#' @param S, phylogenetic tree information matrix
#' @param aggregate, if we aggregate to higher taxonomic level
#' @param b, shape parameter for the inverse gamma hyperprior
#' @param h, scale parameter for the inverse gamma hyperprior
#' @param MRF, if use markov random field prior
#' @param G, phylogenetic tree information matrix used for markov random field prior
#' @param phi_low, lower bound for the dispersion parameter
#' @param mincount,Mimimun number of counts required for each feature to fit the ZINB model
fitZINBDPP <- function(Y, z, s, iter, DPP, S, aggregate, b, h, MRF, G, phi_low = 1, mincount = 2L) {
    .Call(`_HARMONIES_fitZINBDPP`, Y, z, s, iter, DPP, S, aggregate, b, h, MRF, G, phi_low, mincount)
}

